services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        # Restart otomatis jika server reboot
        restart: always
        ports:
            # Port 8081 container dibuka ke Port 80 VPS
            - '8081:80'
        environment:
            # Nilai diambil dari Portainer Environment Variables
            APP_KEY: ${APP_KEY}
            APP_URL: ${APP_URL}
            DB_HOST: mysql
        volumes:
            # HANYA folder storage yang disimpan permanen (untuk upload gambar/file user)
            # Kita TIDAK LAGI me-mount code codingan (.:/app) agar tidak bentrok
            - 'app_storage:/app/storage'
        depends_on:
            - mysql

    mysql:
        image: 'mysql:8.0'
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        volumes:
            # Data database disimpan permanen
            - 'mysql_data:/var/lib/mysql'
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            retries: 3
            timeout: 5s

volumes:
    app_storage:
    mysql_data:
